version: "3"

services:
  api:
    container_name: api
    build: ./backend
    restart: always
    ports:
      - 8000:8000
    env_file:
      - ./backend/.env

  client:
    container_name: client
    build: ./frontend
    restart: always
    ports:
      - 3000:3000
