"""Create enums

Revision ID: 744472ed9f60
Revises: 648390f91a84
Create Date: 2023-10-04 21:22:45.400828

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from api_v1.priorities.schemas import PriorityEnum
from api_v1.states.schemas import StateEnum
from api_v1.roles.schemas import RoleEnum


# revision identifiers, used by Alembic.
revision: str = "744472ed9f60"
down_revision: Union[str, None] = "648390f91a84"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    priorities = op.create_table(
        "priorities",
        sa.Column("title", sa.String(length=16), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("title"),
    )
    op.bulk_insert(priorities, [{"title": v.value} for v in PriorityEnum])
    roles = op.create_table(
        "roles",
        sa.Column("title", sa.String(length=16), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("title"),
    )
    op.bulk_insert(roles, [{"title": v.value} for v in RoleEnum])
    states = op.create_table(
        "states",
        sa.Column("title", sa.String(length=16), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("title"),
    )
    op.bulk_insert(states, [{"title": v.value} for v in StateEnum])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("states")
    op.drop_table("roles")
    op.drop_table("priorities")
    # ### end Alembic commands ###
